FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https
ENV N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
ENV N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-yourpassword}
ENV WEBHOOK_URL=${WEBHOOK_URL}

EXPOSE 5678

CMD ["n8n", "start"]